# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Example' do
    pod 'ScoreboardLabel', :git => 'https://github.com/Noambaron/ScoreboardLabel.git'
end

target 'ExampleTests' do

end

